#cloud-config
autoinstall:
  version: 1
  source:
    id: ubuntu-desktop
  identity:
    hostname: LPT-0
    username: kukuruz
    password: $6$4YUDP5jb24rX/J8N$v8XjXMgtIsPc1mvE/aJf6U36eDpeX.X0FpGvh0bkGY5eNmnEa8GikZ775hCPhcikhAhD2ks52.gphDNLD6W/f1
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  ssh:
    allow-pw: true
    install-server: true
  storage:
    config:
      - id: disk0
        type: disk
        match:
          size: largest
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        name: ''
        grub_device: true
        keep: false
        overwrite: false
        device: "/dev/sda"
      - id: partition0
        type: partition
        size: 1G
        flag: boot
        number: 1
        device: disk0
        preserve: false
        grub_device: true
      - id: partition1
        type: partition
        size: -1
        number: 2
        device: disk0
        preserve: false
      - id: cryptsetup1
        type: luks
        device: partition1
        preserve: false
        password: aim
        keysize: 256
        cipher: aes-xts-plain64
        name: cryptroot
      - id: lvm_volgroup
        type: lvm_volgroup
        devices:
          - cryptsetup1
        name: vgubuntu
      - id: lvm_root
        type: lvm_partition
        size: 20G
        volgroup: lvm_volgroup
        name: lv_root
      - id: lvm_home
        type: lvm_partition
        size: -1
        volgroup: lvm_volgroup
        name: lv_home
      - id: fs_boot
        type: format
        fstype: ext4
        volume: partition0
      - id: fs_root
        type: format
        fstype: ext4
        volume: lvm_root
      - id: fs_home
        type: format
        fstype: ext4
        volume: lvm_home
      - id: mount_boot
        type: mount
        device: fs_boot
        path: /boot
      - id: mount_root
        type: mount
        device: fs_root
        path: /
      - id: mount_home
        type: mount
        device: fs_home
        path: /home
