#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: yes
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    username: user
    hostname: LPT-68
    password: '$6$XQ1Joh/DRxp8khAY$TFK9i243b3ANadRCtcgk1.X/LXOi8/yp7Ou.NHJZYbwTeMIUSc73DDrdA3rcvsgwjND.rgpfL1ECn9twxkFBJ0'
  ssh:
    install-server: true
    allow-pw: true
  storage:
    config:
      - type: disk
        id: disk
        ptable: gpt
        wipe: superblock
        name: system
      - type: partition
        id: efipart
        device: disk
        size: 2G
        flag: boot
        grub_device: true
        wipe: superblock
        number: 1
      - type: partition
        id: bootpart
        device: disk
        size: 5G
        wipe: superblock
        number: 2
      - id: pv
        type: partition
        device: disk
        size: -1
      - id: nvme0n1p3_crypt
        type: dm_crypt
        volume: pv
        preserve: false
        key: '123'
      - id: volumegroup
        name: volgroup
        type: lvm_volgroup
        devices: [ nvme0n1p3_crypt ]
        preserve: false
        key: '123'
        volume: pv
      - id: lv_root
        name: root
        volgroup: volumegroup
        size: 35G
        type: lvm_partition
      - id: lv_home
        name: home
        volgroup: volumegroup
        size: -1
        type: lvm_partition
      - type: format
        id: efipart_fs
        volume: efipart
        fstype: fat32
        label: efi
      - type: format
        id: bootpart_fs
        volume: bootpart
        fstype: ext4
        label: boot
      - type: format
        id: root_fs
        volume: lv_root
        preserve: false
        fstype: ext4
        label: root
      - type: format
        id: home_fs
        volume: lv_home
        preserve: false
        fstype: ext4
        label: home
      - type: mount
        id: efipart-mount
        device: efipart_fs
        path: /boot/efi
      - type: mount
        id: bootpart-mount
        device: bootpart_fs
        path: /boot
      - type: mount
        id: root_mount
        device: root_fs
        path: /
      - type: mount
        id: home_mount
        device: home_fs
        path: /home