#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: yes
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    username: egidio
    hostname: linuxconfig
    password: '$6$XQ1Joh/DRxp8khAY$TFK9i243b3ANadRCtcgk1.X/LXOi8/yp7Ou.NHJZYbwTeMIUSc73DDrdA3rcvsgwjND.rgpfL1ECn9twxkFBJ0'
  ssh:
    install-server: true
    allow-pw: true
  storage:
    config:
      - type: disk
        id: disk
        ptable: gpt
        path: /dev/sda
        wipe: superblock
        name: system
      - type: partition
        id: efipart
        device: disk
        size: 600M
        flag: boot
        grub_device: true
        wipe: superblock
        number: 1
      - type: partition
        id: bootpart
        device: disk
        size: 5G
        wipe: superblock
        number: 2
      - type: partition
        id: root
        name: root
        size: 30G
        device: disk
        wipe: superblock
        number: 3
      - type: partition
        id: home
        name: home
        size: 50G
        device: disk
        wipe: superblock
        number: 4
      - type: dm_crypt
        id: crypt-root
        volume: root
        dm_name: crypt-root
        key: setup
      - type: dm_home
        id: crypt-home
        volume: home
        dm_name: crypt-home
        key: setup
      - type: format
        id: efipart_fs
        volume: efipart
        fstype: fat32
        label: efi
      - type: format
        id: bootpart_fs
        volume: bootpart
        fstype: ext4
        label: boot
      - type: format
        id: root_fs
        volume: crypt-root
        fstype: ext4
        label: root
      - type: format
        id: home_fs
        volume: crypt-home
        fstype: ext4
        label: home
      - type: mount
        id: efipart-mount
        device: efipart_fs
        path: /boot/efi
      - type: mount
        id: bootpart-mount
        device: bootpart_fs
        path: /boot
      - type: mount
        id: root_mount
        device: root_fs
        path: /
      - type: mount
        id: home_mount
        device: home_fs
        path: /home
