#cloud-config
autoinstall:
  version: 1
  source:
    id: ubuntu-server-minimal
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    username: egidio
    hostname: linuxconfig
    password: '$6$XQ1Joh/DRxp8khAY$TFK9i243b3ANadRCtcgk1.X/LXOi8/yp7Ou.NHJZYbwTeMIUSc73DDrdA3rcvsgwjND.rgpfL1ECn9twxkFBJ0'
  ssh:
    install-server: true
    allow-pw: true
  storage:
    config:
      - id: disk
        type: disk
        ptable: gpt
        device: /dev/sda
      - id: efipart
        type: partition
        device: disk
        size: 600M
        flag: boot
      - id: bootpart
        type: partition
        device: disk
        size: 1G
      - id: pvpart
        type: partition
        device: disk
        size: -1
      - id: vg0
        type: lvm_volgroup
        name: vg0
        devices:
          - pvpart
      - id: root_lv
        type: lvm_partition
        name: lv_root
        volgroup: vg0
        size: 45G
      - id: home_lv
        type: lvm_partition
        name: lv_home
        volgroup: vg0
        size: 50G
      - id: efipart_fs
        type: format
        volume: efipart
        fstype: fat32
      - id: bootpart_fs
        type: format
        volume: bootpart
        fstype: ext4
      - id: root_fs
        type: format
        volume: root_lv
        fstype: ext4
      - id: home_fs
        type: format
        volume: home_lv
        fstype: ext4
      - id: efipart-mount
        type: mount
        device: efipart_fs
        path: /boot/efi
      - id: bootpart-mount
        type: mount
        device: bootpart_fs
        path: /boot
      - id: root_lv_mount
        type: mount
        device: root_fs
        path: /
      - id: home_lv_mount
        type: mount
        device: home_fs
        path: /home
