#cloud-config
autoinstall:
  version: 1
  source:
    id: ubuntu-desktop
  identity:
    hostname: LPT-0
    username: kukuruz
    password: $6$4YUDP5jb24rX/J8N$v8XjXMgtIsPc1mvE/aJf6U36eDpeX.X0FpGvh0bkGY5eNmnEa8GikZ775hCPhcikhAhD2ks52.gphDNLD6W/f1
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  ssh:
    allow-pw: true
    install-server: true
  storage:
    layout:
      name: lvm
      password: $6$4YUDP5jb24rX/J8N$v8XjXMgtIsPc1mvE/aJf6U36eDpeX.X0FpGvh0bkGY5eNmnEa8GikZ775hCPhcikhAhD2ks52.gphDNLD6W/f1
    config:
      - type: partition
        id: boot-partition
        size: 10G
        flag: boot
      - type: partition
        id: root-partition
        size: 32G
      - type: partition
        id: home-partition
        size: 55G
      - id: cryptroot
        type: luks
        device: root-partition
        password: aim
      - id: crypthome
        type: luks
        device: home-partition
        password: aim
      - id: lvm-root
        type: lvm_partition
        volgroup: vgubuntu
        name: lv_root
        size: -1
        device: cryptroot
      - id: lvm-home
        type: lvm_partition
        volgroup: vgubuntu
        name: lv_home
        size: -1
        device: crypthome
      - id: fs-boot
        type: format
        fstype: ext4
        volume: boot-partition
      - id: fs-root
        type: format
        fstype: ext4
        volume: lvm-root
      - id: fs-home
        type: format
        fstype: ext4
        volume: lvm-home
      - id: mount-boot
        type: mount
        path: /boot
        device: fs-boot
      - id: mount-root
        type: mount
        path: /
        device: fs-root
      - id: mount-home
        type: mount
        path: /home
        device: fs-home
