#cloud-config
autoinstall:
  version: 1
  source:
    id: ubuntu-desktop
  identity:
    hostname: LPT-0
    username: kukuruz
    password: $6$eETFZuc/LI7QzZ7A$oTvQ.ED4NaDWHLKs.tmdZukDC/qbcx0XQ08OXdvQVScCKEPlElKWstJ9hOjitR2Ni0YZx95wmrD0m8BWVG0kV1
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  ssh:
    allow-pw: true
    install-server: true
  storage:
    layout:
      name: lvm
      password: $6$eETFZuc/LI7QzZ7A$oTvQ.ED4NaDWHLKs.tmdZukDC/qbcx0XQ08OXdvQVScCKEPlElKWstJ9hOjitR2Ni0YZx95wmrD0m8BWVG0kV1
    config:
      - type: partition
        id: boot-partition
        size: 10G
        flag: boot
      - type: partition
        id: root-partition
        size: 32G
      - type: partition
        id: home-partition
        size: 55G
      - id: cryptroot
        type: luks
        device: root-partition
        password: $6$eETFZuc/LI7QzZ7A$oTvQ.ED4NaDWHLKs.tmdZukDC/qbcx0XQ08OXdvQVScCKEPlElKWstJ9hOjitR2Ni0YZx95wmrD0m8BWVG0kV1
      - id: crypthome
        type: luks
        device: home-partition
        password: $6$eETFZuc/LI7QzZ7A$oTvQ.ED4NaDWHLKs.tmdZukDC/qbcx0XQ08OXdvQVScCKEPlElKWstJ9hOjitR2Ni0YZx95wmrD0m8BWVG0kV1
      - id: lvm-root
        type: lvm_partition
        volgroup: vgubuntu
        name: lv_root
        size: -1
        device: cryptroot
      - id: lvm-home
        type: lvm_partition
        volgroup: vgubuntu
        name: lv_home
        size: -1
        device: crypthome
      - id: fs-boot
        type: format
        fstype: ext4
        volume: boot-partition
      - id: fs-root
        type: format
        fstype: ext4
        volume: lvm-root
      - id: fs-home
        type: format
        fstype: ext4
        volume: lvm-home
      - id: mount-boot
        type: mount
        path: /boot
        device: fs-boot
      - id: mount-root
        type: mount
        path: /
        device: fs-root
      - id: mount-home
        type: mount
        path: /home
        device: fs-home
