#cloud-config
autoinstall:
  version: 1
  source:
    id: ubuntu-desktop-minimal
  locale: en_US.UTF-8
  keyboard:
    layout: us
  identity:
    hostname: LPT-0
    username: kukuruz
    password: $6$eETFZuc/LI7QzZ7A$oTvQ.ED4NaDWHLKs.tmdZukDC/qbcx0XQ08OXdvQVScCKEPlElKWstJ9hOjitR2Ni0YZx95wmrD0m8BWVG0kV1
  ssh:
    allow-pw: true
    install-server: true
  storage:
    config:
      - id: disk0
        name: disk0
        type: disk
        ptable: gpt
        wipe: superblock-recursive

      - id: efipart
        type: partition
        device: disk-vda
        offset: 1048576
        size: 600M
        flag: boot
        grub_device: true

      - id: boot
        type: partition
        device: disk0
        size: 2G
      
      - id: pvpart
        type: partition
        device: disk-vda
        size: -1

      - id: pvpart-crypt
        type: dm_crypt
        vilume: pvpart
        key: aim

      - id: vg0
        type: lvm_volgroup
        name: vg0
        devices:
          - pvpart-crypt

      - id: root
        type: lvm_partition
        name: root
        volgroup: vg0
        size: 35G
 
      - id: home
        type: lvm_partition
        name: home
        volgroup: vg0
        size: 50G

      - id: efipart_fs
        type: format
        volume: efipart
        fstype: fat32

      - id: boot_fs
        type: format
        volume: boot
        fstype: ext4

      - id: root_fs
        type: format
        volume: root
        fstype: ext4

      - id: home_fs
        type: format
        volume: home
        fstype: ext4

      - id: efipart-mount
        type: mount
        device: efipart_fs
        path: /boot/efi

      - id: boot-mount
        type: mount
        device: bootpart_fs
        path: /boot

      - id: root_mount
        type: mount
        device: root_fs
        path: /

      - id: home_mount
        type: mount
        device: home_fs
        path: /home
